"""Initial Migration

Revision ID: 5dec31b7fd34
Revises: b2b4300c5759
Create Date: 2019-09-26 15:15:03.789058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dec31b7fd34'
down_revision = 'b2b4300c5759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
